trapu l'erreur là
RuntimeError: one of the variables needed for gradient computation has
been modified by an inplace operation: [torch.cuda.FloatTensor [32, 1,
128, 128]], which is output 0 of UnsqueezeBackward0, is at version 1;
expected version 0 instead. Hint: enable anomaly detection to find the
operation that failed to compute its gradient, with
torch.autograd.set_detect_anomaly(True).